### PR TITLE
Update to Apache Jena 4.7.0

### PR DESCRIPTION
**Pull request by afs**
Java version set to 11.
Bump TARQ version to 1.3.
Support for RDF-star https://github.com/tarql/tarql/issues/81
Add handling for BOM  https://github.com/tarql/tarql/issues/94

### CODE REVIEW

**Comment by LorenzBuehmann** [comment]
@afs latest version bump to 4.7.0 leads to a startup error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.jena.rdf.model.impl.ResourceImpl.fresh(ResourceImpl.java:140)
	at org.apache.jena.rdf.model.impl.ResourceImpl.<init>(ResourceImpl.java:86)
	at org.apache.jena.rdf.model.ResourceFactory$Impl.createResource(ResourceFactory.java:312)
	at org.apache.jena.rdf.model.ResourceFactory.createResource(ResourceFactory.java:92)
	at org.apache.jena.vocabulary.RDFS.resource(RDFS.java:35)
	at org.apache.jena.vocabulary.RDFS$Init.Class(RDFS.java:68)
	at org.apache.jena.vocabulary.RDFS.<clinit>(RDFS.java:40)
	at org.apache.jena.shared.PrefixMapping.<clinit>(PrefixMapping.java:219)
	at org.apache.jena.sparql.ARQConstants.<clinit>(ARQConstants.java:114)
	at org.apache.jena.sparql.function.FunctionRegistry.get(FunctionRegistry.java:66)
	at org.apache.jena.sparql.function.FunctionRegistry.get(FunctionRegistry.java:53)
	at org.deri.tarql.TarqlQuery.registerFunctions(TarqlQuery.java:27)
	at org.deri.tarql.TarqlQuery.<clinit>(TarqlQuery.java:21)
	at org.deri.tarql.tarql.<clinit>(tarql.java:56)
Caused by: org.apache.jena.sparql.ARQException: Context key is null
	at org.apache.jena.sparql.util.Context.mapPut(Context.java:75)
	at org.apache.jena.sparql.util.Context.set(Context.java:137)
	at org.apache.jena.sparql.function.FunctionRegistry.set(FunctionRegistry.java:70)
	at org.apache.jena.sparql.function.FunctionRegistry.init(FunctionRegistry.java:48)
	at org.apache.jena.query.ARQ.init(ARQ.java:640)
	at org.apache.jena.sparql.system.InitARQ.start(InitARQ.java:29)
	at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
	at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88)
	at org.apache.jena.graph.NodeFactory.<clinit>(NodeFactory.java:32)
	... 14 more
```
with 4.5.0 everything is fine.

Moving the second static block with the Jena init part before the tarql specific static block where function will be registred solves this problem.

**Comment by LorenzBuehmann** [comment]
There is a second issue now with 4.7.0: it doesn't produce any triples because of some IRI behaviour changes I guess? It only produces triples if a base URI has been set, e.g. via commandline flag
`./bin/tarql --base file://$PWD test.tarql test.csv > out.ttl`

Is this intended?

**Comment by afs** [comment]
> ./bin/tarql --base file://$PWD test.tarql test.csv > out.ttl

Complete, _minimal_ example of the difference please!

What do you expect?
Have you asked your colleagues? apache/jena#1272

**Comment by LorenzBuehmann** [comment]
I tested a fresh Git clone of the branch on a different server. After fixing the startup error, I'm getting the same unexpected result. 

I expect triples being generated of course. With Jena 4.5.0 the TARQL queries have been working without specifying a base URI - especially given that there are no relative URIs in the TARQL query.

I attached a sample CSV and TARQL file.

Usage: 

```
bin/tarql sample.tarql sample.csv
```
Output is empty

------
With specifying a base URI via CLI 
```
bin/tarql --base http://base.org sample.tarql sample.csv
```
I get
``` turtle
BASE           <http://base.org>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

<http://example.org/x>
        <http://example.org/p>  "y" .
```
same expected result indeed if we set the base URI in the TARQL query.

The base URI is useless in the resulting Turtle, but I can't get it working without and I don't see why we should set a base URI here at all. I must be missing something, but I also know that you did a lots of work between 4.5.0 and 4.7.0 on the IRI part.

But for TARQL users I guess the current result would be unexpected.

Nevertheless, thanks for the fork and the update.

### Artifacts:

[sample.zip](https://github.com/tarql/tarql/files/10887671/sample.zip)

**Comment by afs** [comment]
> of course

There is new information in `sample.zip`.

tarql always sets the base URI whether you supply `--base` or not. It defaults to the query name. (Personally, I think it should be the data file).

But a filename is an inappropriate base URI - it's URI-relative. Resolution then fails.

That is fixable.

You could have used `file:sample.tarql`

> Nevertheless

I don't maintain tarql.

**Comment by rjyounes** [comment]
I'm seeing the following difference between this branch and tarql 1.2, also having to do with BASE definitions, but it sounds like a slightly different issue.

This version of tarql adds a BASE declaration to the output using the name of the tarql file. E.g., 

```
tarql-1.3 centuries.tq > centuries.ttl
```
Adds 

```
BASE <centuries.tq> 
```
to the top of the file.  Tarql 1.2 doesn't do this.

I don't know whether this is technically malformed, but the [EDM serializer](https://github.com/edmcouncil/rdf-toolkit) rejects it as a syntax error. 

The workaround (other than deleting the line) is to specify a well-formed value for BASE:

```
tarql-1.3 --base "https://data.treasuryoflives.org/"  centuries.tq > centuries.ttl
```
Gives:
```
BASE <https://data.treasuryoflives.org/>
```
which I don't need, but at least is well-formed.

Is it possible that this version of tarql turns the `write-base` option on by default?

**Comment by afs** [comment]
@rjyounes - What error does the EDM serializer give?

It is a corner-case but "BASE \<relativeURI>" is legal - it means resolve the new base <relativeURI> against the current one (the starting one from where it is executed or an earlier BASE in the file.

But may be it is complaining about `BASE` vs `@base`.

**Comment by rjyounes** [comment]
@afs I've copied the serializer exception below:

```
11:05:31.082 ERROR o.e.r.rio.helpers.ParseErrorLogger - [Rio fatal] Not a valid (absolute) IRI: /centuries.tq (1, -1)
11:05:31.084 ERROR o.e.r.runner.RdfToolkitRunner - RdfFormatter: stopped by unexpected exception:
11:05:31.085 ERROR o.e.r.runner.RdfToolkitRunner - Unable to parse input file: /Users/ryounes/Projects/tol/tarql/centuries/centuries.ttl
11:05:31.085 ERROR o.e.r.runner.RdfToolkitRunner - Command line arguments: [-tfmt, turtle, -sdt, explicit, -dtd, -ibn, -s, centuries.ttl, -t, centuries.ttl.bak]
11:05:31.085 ERROR o.e.r.runner.RdfToolkitRunner - RDFParseException: Not a valid (absolute) IRI: /centuries.tq [line 1]
11:05:31.086 ERROR o.e.r.runner.RdfToolkitRunner - org.eclipse.rdf4j.rio.RDFParseException: Not a valid (absolute) IRI: /centuries.tq [line 1]
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:373)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:772)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1310)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:424)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:402)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:937)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseBase(TurtleParser.java:297)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseDirective(TurtleParser.java:229)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:192)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:162)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:125)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:299)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:265)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:237)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.readModel(RdfToolkitRunner.java:264)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.runOnFile(RdfToolkitRunner.java:179)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.run(RdfToolkitRunner.java:106)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.run(RdfFormatter.java:64)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.main(RdfFormatter.java:47)
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: /centuries.tq
        at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:75)
        at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:64)
        at org.eclipse.rdf4j.model.impl.SimpleValueFactory.createIRI(SimpleValueFactory.java:102)
        at org.eclipse.rdf4j.rio.helpers.RDFStarDecodingValueFactory.createIRI(RDFStarDecodingValueFactory.java:42)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:422)
        ... 15 more
```
It doesn't like the relative IRI for the BASE.

You're right, I hadn't noticed that tarql 1.3 (unlike 1.2) is outputting BASE and PREFIX rather than @base and @prefix, but the serializer is not tripping over it when the value is an absolute IRI.

Should this be considered a bug in the EDM serializer? But aside from that, defining the tarql file itself as the BASE seems odd.

**Comment by rjyounes** [comment]
Submitted [issue to rdf-toolkit repository](https://github.com/edmcouncil/rdf-toolkit/issues/48).

**Comment by afs** [comment]
I'm not able to reproduce this locally but maybe I have a version ahead of what is being used. 

`IRI: /centuries.tq` --where does the "/" come from?

Could you show the query and the CSV file?

**Comment by rjyounes** [comment]
I'm attaching a zip file with the files you've requested. I don't know why the serializer references `/centuries.tq` since I don't see that anywhere in the tarql output. It's definitely related to `BASE <centuries.tq>`, since there's no error from the serializer when it's removed.

[centuries.zip](https://github.com/tarql/tarql/files/11264113/centuries.zip)

**Comment by afs** [comment]
It works for me using the [afs:jena-update](https://github.com/afs/tarql/tree/jena-update). BASE is not output unless `--base` is used.

**Comment by afs** [comment]
With the latest state of [afs:jena-update](https://github.com/afs/tarql/tree/jena-update) -- which is commit eb44178 -- there is no BASE printed unless `--base` is used.

**Comment by afs** [comment]
Closing this PR - it's nearly a year old. 

I need to clear out old things to be able to better see active PRs -- RDF 1.2 has a lot of git-related work.

The [afs/tarql:jena-update](https://github.com/afs/tarql/tree/jena-update) is still available. I can't promise to keep it up-to-date but I have updated to Jena 4.8.0. I also bumped the branch to Java17 (Javadoc production with Java11 is broken).

**Pull request closed without merging**
